# Generated by Django 5.0.4 on 2024-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=4)),
                ('is_verified', models.BooleanField(default=False)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('activated_invite_code', models.BooleanField(default=False)),
            ],
        ),
    ]
